spring:
  application:
    name: ibtss
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVERNAME}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    hibernate:
      ddl-auto: update
      dialect: MySQL8Dialect
server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /ibtss
  host:
    url: ${SERVER_HOST}

jwt:
  signerKey: ${SIGNER_KEY}

