spring:
  application:
    name: ibtss
  datasource:
    url: ${DB_URL}?zeroDateTimeBehavior=CONVERT_TO_NULL
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVERNAME}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: MySQL8Dialect
server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /ibtss
  host:
    url: ${SERVER_HOST}

jwt:
  signerKey: ${SIGNER_KEY}
payos:
  client-id: ${CLIENT_ID}
  api-key: ${API_KEY}
  check-sum-key: ${CHECK_SUM_KEY}



